version: "3"
services:
  app:
    container_name: app
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    env_file: config.py

  mysql:
    container_name: mysql
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: 127.0.0.1
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5
    volumes:
      - ./db:/docker-entrypoint-initdb.d
