version: "3"
services:
  app:
    container_name: app
    build: ./
    ports:
      - "8080:8000"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0.32
    ports:
      - "3316:3306"
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: 127.0.0.1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
